#ifndef _CUTSCENE_EVENTS_PROTOTYPES_H_
#define _CUTSCENE_EVENTS_PROTOTYPES_H_

#include "scene/cutscene/events/debug/terminal_print_cutscene_event.h"
#include "scene/cutscene/events/system/enable_system_cutscene_event.h"
#include "scene/cutscene/events/system/disable_system_cutscene_event.h"
#include "scene/cutscene/events/camera/camera_move_event.h"
#include "scene/cutscene/events/camera/camera_zoom_event.h"
#include "scene/cutscene/events/scene/scene_switch_cutscene_event.h"
#include "scene/cutscene/events/shader/shader_uniform_f32_change_cutscene_event.h"
#include "scene/cutscene/events/entity/spawn_entity_cutscene_event.h"
#include "scene/cutscene/events/dialogue/spawn_dialogue_tab_cutscene_event.h"
#include "scene/cutscene/events/entity/entity_transparency_change_event.h"
#include "scene/cutscene/events/dialogue/spawn_dialogue_text_cutscene_event.h"
#include "scene/cutscene/events/entity/animate_static_text_cutscene_event.h"
#include "scene/cutscene/events/dialogue/spawn_dialogue_speaker_icon_cutscene_event.h"
#include "scene/cutscene/events/entity/entity_position_set_event.h"
#include "scene/cutscene/events/entity/entity_position_move_event.h"
#include "scene/cutscene/events/entity/entity_position_set_relative_event.h"
#include "scene/cutscene/events/entity/entity_sprite_flip_set_event.h"
#include "scene/cutscene/events/entity/entity_spriterenderer_set_texture_event.h"
#include "scene/cutscene/events/entity/destroy_entity_cutscene_event.h"
#include "scene/cutscene/events/scene/scene_save_checkpoint.h"
#include "scene/cutscene/events/scene/scene_load_checkpoint.h"
#include "scene/cutscene/events/run_cutscene_cutscene_event.h"
#include "scene/cutscene/events/entity/dynamic_entity_spriteanimation_set_animation_event.h"
#include "scene/cutscene/events/entity/static_entity_spriteanimation_set_animation_event.h"
#include "scene/cutscene/events/entity/find_dynamic_entity_cutscene_event.h"
#include "scene/cutscene/events/wait_cutscene_event.h"
#include "scene/cutscene/events/scene/spawn_pause_text_cutscene_event.h"
#include "scene/cutscene/events/entity/find_static_entity_cutscene_event.h"
#include "scene/cutscene/events/entity/entity_collect_event.h"
#include "scene/cutscene/events/scene/reduce_timeline_frames.h"
#include "scene/cutscene/events/sound/sound_loop_cutscene_event.h"

#endif
