#ifndef _ECS_COMPONENTS_H_
#define _ECS_COMPONENTS_H_

#include "ecs_sprite_renderer.h"
#include "ecs_spritesheet_renderer.h"
#include "ecs_2d_physics_rigidbody.h"
#include "ecs_aabb_collider.h"
#include "ecs_acceleration.h"
#include "ecs_friction.h"
#include "ecs_gravity.h"
#include "ecs_movable_aabb_collider.h"
#include "ecs_player_controller.h"
#include "ecs_positioned.h"
#include "ecs_scaled.h"
#include "ecs_sprite_animation.h"
#include "ecs_sprite_flip.h"
#include "ecs_velocity.h"
#include "ecs_physics_positioned.h"
#include "ecs_camera_follow.h"
#include "ecs_player_jump.h"
#include "ecs_player_debug_metrics.h"
#include "ecs_box_collider_mesh.h"
#include "ecs_tilemap_renderer.h"
#include "ecs_state_machine_base.h"
#include "ecs_crab_controller.h"
#include "ecs_parallax_sprite_renderer_back.h"
#include "ecs_parallax_sprite_renderer_front.h"
#include "ecs_player_time_jump_controller.h"
#include "ecs_sound_emitter.h"
#include "ecs_pro_renderer.h"
#include "ecs_instancing_renderer.h"
#include "ecs_text_renderer.h"
#include "ecs_transparency.h"
#include "ecs_sprite_animation_auto.h"
#include "ecs_sprite_animation_manual.h"
#include "ecs_deadly.h"
#include "ecs_star_controller.h"

#include "ecs_button.h"
#include "ecs_interactive.h"
#include "ecs_interactive_press.h"
#include "ecs_interactive_collision.h"
#include "ecs_trigger_aabb_collider.h"
#include "ecs_popup_renderer.h"

#include "ecs_popup.h"
#include "ecs_speak_popup.h"
#include "ecs_use_popup.h"
#include "ecs_checkpoint_popup.h"

#endif
