#ifndef _ECS_COMPONENTS_H_
#define _ECS_COMPONENTS_H_

#include "ecs/gfx/ecs_sprite_renderer.h"
#include "ecs/gfx/ecs_spritesheet_renderer.h"
#include "ecs/motion/ecs_2d_physics_rigidbody.h"
#include "ecs/motion/ecs_aabb_collider.h"
#include "ecs/motion/ecs_acceleration.h"
#include "ecs/motion/ecs_friction.h"
#include "ecs/motion/ecs_gravity.h"
#include "ecs/motion/ecs_movable_aabb_collider.h"
#include "ecs/controllers/ecs_player_controller.h"
#include "ecs/motion/ecs_positioned.h"
#include "ecs/motion/ecs_scaled.h"
#include "ecs/gfx/ecs_sprite_animation.h"
#include "ecs/gfx/ecs_sprite_flip.h"
#include "ecs/motion/ecs_velocity.h"
#include "ecs/motion/ecs_physics_positioned.h"
#include "ecs/controllers/ecs_camera_follow.h"
#include "ecs/controllers/ecs_player_jump.h"
#include "ecs/debug/ecs_player_debug_metrics.h"
#include "ecs/motion/ecs_box_collider_mesh.h"
#include "ecs/gfx/ecs_tilemap_renderer.h"
#include "ecs/controllers/ecs_state_machine_base.h"
#include "ecs/controllers/ecs_crab_controller.h"
#include "ecs/gfx/ecs_parallax_sprite_renderer_back.h"
#include "ecs/gfx/ecs_parallax_sprite_renderer_front.h"
#include "ecs/controllers/ecs_player_time_jump_controller.h"
#include "ecs/sound/ecs_sound_emitter.h"
#include "ecs/gfx/ecs_pro_renderer.h"
#include "ecs/gfx/ecs_instancing_renderer.h"
#include "ecs/gfx/ecs_text_renderer.h"
#include "ecs/gfx/ecs_transparency.h"
#include "ecs/gfx/ecs_sprite_animation_auto.h"
#include "ecs/gfx/ecs_sprite_animation_manual.h"
#include "ecs/motion/ecs_deadly.h"
#include "ecs/controllers/ecs_star_controller.h"

#include "ecs/gui/ecs_button.h"
#include "ecs/interactive/ecs_interactive.h"
#include "ecs/interactive/ecs_interactive_press.h"
#include "ecs/interactive/ecs_interactive_collision.h"
#include "ecs/motion/ecs_trigger_aabb_collider.h"
#include "ecs/interactive/ecs_popup_renderer.h"

#include "ecs/interactive/ecs_popup.h"
#include "ecs/interactive/ecs_speak_popup.h"
#include "ecs/interactive/ecs_use_popup.h"
#include "ecs/interactive/ecs_checkpoint_popup.h"
#include "ecs/gfx/ecs_gui_spritesheet_renderer.h"
#include "ecs/gfx/ecs_gui_sprite_renderer.h"
#include "ecs/controllers/ecs_player_collector_controller.h"
#include "ecs/interactive/ecs_collectable.h"
#include "ecs/controllers/ecs_clock_progression_bar_controller.h"
#include "ecs/interactive/ecs_red_crystal_popup.h"

#endif
